### ISSUE TITLE
Grader Bug: MiniFlow > Forward Propagation Solution

### ISSUE THREAD

**Issue by matthewzimmer** [udacity/sdc-issue-reports#127]
I believe the grader software is for Python 2 even though we are supposed to be using Python 3 for this course.

Reason I say this is because I had to use Python 2 syntax for Add constructor. 

Using Python 3 constructor with splat operator threw exception:

Traceback (most recent call last):
  File "vm_main.py", line 33, in <module>
    import main
  File "/tmp/vmuser_ltdrckzxjc/main.py", line 2, in <module>
    import studentMain
  File "/tmp/vmuser_ltdrckzxjc/studentMain.py", line 2, in <module>
    import nn
  File "/tmp/vmuser_ltdrckzxjc/nn.py", line 8, in <module>
    from miniflow import *
  File "/tmp/vmuser_ltdrckzxjc/miniflow.py", line 62
    Neuron.__init__(self, [*inputs])
                           ^
SyntaxError: invalid syntax

**Comment by domluna** [comment]
Hi @matthewzimmer, the classroom currently uses Python 2. I believe there's a transition to Python 3 in the works and I'll look more into when that would be.

**Comment by domluna** [comment]
I'm going to close this and open an issue for getting Python 3 in the classroom.
