### ISSUE TITLE
500 Error for every frame request to drive.py

### ISSUE THREAD

**Issue by paul-o-alto** [udacity/sdc-issue-reports#146]
I see this error in a rapid-fire manner for every frame prediction request from the simulator.

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/eventlet/wsgi.py", line 481, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/socketio/server.py", line 334, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/usr/local/lib/python3.5/dist-packages/engineio/server.py", line 230, in handle_request
    transport, b64)
  File "/usr/local/lib/python3.5/dist-packages/engineio/server.py", line 328, in _handle_connect
    if self._trigger_event('connect', sid, environ, async=False) is False:
  File "/usr/local/lib/python3.5/dist-packages/engineio/server.py", line 357, in _trigger_event
    return self.handlers[event](*args)
  File "/usr/local/lib/python3.5/dist-packages/socketio/server.py", line 472, in _handle_eio_connect
    return self._handle_connect(sid, '/')
  File "/usr/local/lib/python3.5/dist-packages/socketio/server.py", line 395, in _handle_connect
    self.environ[sid]) is False:
  File "/usr/local/lib/python3.5/dist-packages/socketio/server.py", line 462, in _trigger_event
    return self.handlers[namespace][event](*args)
TypeError: connect() takes 1 positional argument but 2 were given

**Comment by paul-o-alto** [comment]
Fixed the script so that connect would succeed, but the simulator never seems to query the telemetry method.

**Comment by paul-o-alto** [comment]
Didn't see the other issue that was already about this. Can go ahead and close it. Will create another one about telemetry issue.
