### ISSUE TITLE
MNIST Mini-batch quiz

### ISSUE THREAD

**Issue by raahil190** [udacity/sdc-issue-reports#467]
While attempting to run it on my machine, the following command :

>>  mnist = input_data.read_data_sets('/datasets/ud730/mnist', one_hot=True)

Gives the following error :
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/c1utt4r/miniconda3/envs/IntroToTensorFlow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/mnist.py", line 211, in read_data_sets
    SOURCE_URL + TRAIN_IMAGES)
  File "/home/c1utt4r/miniconda3/envs/IntroToTensorFlow/lib/python3.6/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py", line 205, in maybe_download
    gfile.MakeDirs(work_directory)
  File "/home/c1utt4r/miniconda3/envs/IntroToTensorFlow/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 301, in recursive_create_dir
    pywrap_tensorflow.RecursivelyCreateDir(compat.as_bytes(dirname), status)
  File "/home/c1utt4r/miniconda3/envs/IntroToTensorFlow/lib/python3.6/contextlib.py", line 89, in __exit__
    next(self.gen)
  File "/home/c1utt4r/miniconda3/envs/IntroToTensorFlow/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 469, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.PermissionDeniedError: /datasets

**Comment by shimmeringvoid** [comment]
I had the same problem. You don't have '/datasets/ud730/mnist' on your local system. I had to change that to '/tmp/tensorflow/mnist/input_data' on my Ubuntu system.
