### ISSUE TITLE
CUDA Broken on AWS AMI

### ISSUE THREAD

**Issue by dsilver829** [udacity/sdc-issue-reports#598]
Several students have reported issues with this: https://discussions.udacity.com/t/latest-nvidia-drivers-broken-on-g2-instances/231377

Looks like we may have to update the AMI.

**Comment by swwelch** [comment]
Looks like the same solution was also posted here:
https://discussions.udacity.com/t/failed-to-train-with-gpu-on-aws/231187

**Comment by Daniel-Prado** [comment]
I also just found out that the Tensorflow version in the AMI image is quite outdated (0.12.1).
This was causing issues when porting my code... Of course I could update tensorflow, but I don't dare to mess around it ... I don't want to broke the instance before finishing P2.
I strongly suggest that in order to avoid these issues, the staff provides an script or guidelines to set up a working image by ourselves in Amazon AWS with GPU support, instead of just the AMI that will become outdated every month...

**Comment by killermonkeys** [comment]
+1 to Daniel's comments... I think at least adding documentation that suggests whether CUDA detected the GPU and/or a script in the AMI that tests everything is working.

The problem is that if you don't have a GPU, you don't know what the log messages should look like and you would assume the AMI is working properly.

**Comment by alexandergregory** [comment]
Hi! 
Are you able to roll out the CarND AMI Update to other AWS regions? I'm logging a request to increase my limit in Oregon as it's not yet available in the Sydney region.
Cheers,
Alex

**Comment by baumanab** [comment]
The new AMI released this summer likely resolve this issue, but we will verify.

**Comment by CodingCanuck** [comment]
I'm still seeing this.

I'm installing the latest version of tensorflow-gpu on the API to workaround the Illegal Instruction error on g2.2xlarge instances ( https://github.com/udacity/sdc-issue-reports/issues/1186 ). 

I then try to run ~/inference-walkthrough/src$ python graph_utils.py , and get errors about cuda and nvidia version mismatches:

ubuntu@<aws-ip-redacted>:~/inference-walkthrough/src$ python graph_utils.py 
XLA None
2017-10-29 23:52:51.672978: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-29 23:52:51.673018: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-29 23:52:51.673036: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-29 23:52:51.680693: E tensorflow/stream_executor/cuda/cuda_driver.cc:406] failed call to cuInit: CUDA_ERROR_NO_DEVICE
2017-10-29 23:52:51.680750: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:158] retrieving CUDA diagnostic information for host: ip-172-31-18-54
2017-10-29 23:52:51.680769: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:165] hostname: ip-172-31-18-54
2017-10-29 23:52:51.680825: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:189] libcuda reported version is: 384.90.0
2017-10-29 23:52:51.681371: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:369] driver version file contents: """NVRM version: NVIDIA UNIX x86_64 Kernel Module  375.66  Mon May  1 15:29:16 PDT 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
"""
2017-10-29 23:52:51.681416: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:193] kernel reported version is: 375.66.0
2017-10-29 23:52:51.681435: E tensorflow/stream_executor/cuda/cuda_diagnostics.cc:303] kernel version 375.66.0 does not match DSO version 384.90.0 -- cannot find working devices in this configuration
Traceback (most recent call last):
  File "graph_utils.py", line 70, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "graph_utils.py", line 62, in main
    sess, ops = load_graph(FLAGS.graph)
  File "graph_utils.py", line 21, in load_graph
    data = f.read()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 118, in read
    self._preread_check()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/lib/io/file_io.py", line 78, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/compat.py", line 65, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got None

**Comment by CodingCanuck** [comment]
Note the update to https://github.com/udacity/sdc-issue-reports/issues/1186 : I suspect that version of tensorflow provided in the current AMI was built with compiler flags that make it incompatible with any of amazon's G2 instances

**Comment by mvirgo** [comment]
The AMI should be loading with the correct driver now; have also added instructions to the classroom based on David's linked forum post in case this pops up again for any students.
