### ISSUE TITLE
Incomplete instructions for installing Keras

### ISSUE THREAD

**Issue by rm51** [udacity/sdc-issue-reports#62]
When following the instructions to install Keras I got the following error.

>>> import keras
Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/r/anaconda/envs/keras/lib/python3.5/site-packages/keras/__init__.py", line 2, in <module>
    from . import backend
  File "/Users/r/anaconda/envs/keras/lib/python3.5/site-packages/keras/backend/__init__.py", line 64, in <module>
    from .tensorflow_backend import *
  File "/Users/r/anaconda/envs/keras/lib/python3.5/site-packages/keras/backend/tensorflow_backend.py", line 1, in <module>
    import tensorflow as tf
ImportError: No module named 'tensorflow'

**Comment by domluna** [comment]
Keras uses the TensorFlow as the default backend so you'll need to install it before installing keras, or reinstall keras after.

https://www.tensorflow.org/versions/r0.11/get_started/index.html

**Comment by rm51** [comment]
It would be helpful to include:
conda install -c conda-forge tensorflow
So that users don't have to scroll back to the TensorFlow lab to see how to install it since previously we installed it in a different conda environment.  For example in Step 1 after:
source activate keras

**Comment by domluna** [comment]
Fixed.
