### ISSUE TITLE
Cannot Purchase Term 2

### ISSUE THREAD

**Issue by chmod600** [udacity/sdc-issue-reports#756]
Purchase link for Term 2 keeps loading indefinitely. There is a JS issue (checked in the browser console)

Uncaught TypeError: Cannot read property 'key' of undefined
    at r.handleEnrollClick (https://classroom.udacity.com/js/4.c0357.js:22:8478)
    at Object.handleClick (https://classroom.udacity.com/js/1.1805a.js:1:7036)
    at Object.r (https://classroom.udacity.com/js/vendor.459ac.js:7:24909)
    at u (https://classroom.udacity.com/js/vendor.459ac.js:7:20983)
    at Object.a [as executeDispatchesInOrder] (https://classroom.udacity.com/js/vendor.459ac.js:7:21198)
    at h (https://classroom.udacity.com/js/vendor.459ac.js:6:23776)
    at v (https://classroom.udacity.com/js/vendor.459ac.js:6:23902)
    at Array.forEach (native)
    at r (https://classroom.udacity.com/js/vendor.459ac.js:8:26683)
    at Object.processEventQueue (https://classroom.udacity.com/js/vendor.459ac.js:6:24980)
    at r (https://classroom.udacity.com/js/vendor.459ac.js:12:21202)
    at Object.handleTopLevel [as _handleTopLevel] (https://classroom.udacity.com/js/vendor.459ac.js:12:21304)
    at i (https://classroom.udacity.com/js/vendor.459ac.js:12:21734)
    at r.perform (https://classroom.udacity.com/js/vendor.459ac.js:7:4300)
    at Object.batchedUpdates (https://classroom.udacity.com/js/vendor.459ac.js:12:19982)
    at Object.i [as batchedUpdates] (https://classroom.udacity.com/js/vendor.459ac.js:5:30787)

**Comment by jessluls** [comment]
Sorry we never got back to you on this but I think this problem is resolved now! Were you able to pay for Term 2? If not, feel free to contact me on Slack. I'm @jessica.
