### ISSUE TITLE
Can’t save autonomous run of successful model

### ISSUE THREAD

**Issue by adriantorrie** [udacity/sdc-issue-reports#830]
I try to save an autonomous run with the following command:

> python drive.py model/20170529_125223_10_10_01_025_0_085/model_02_0.0200.h5 run1

The car runs fine and makes it around the track, however the following error fires off each time it appears the sim is attempting to save to disk:
```sh
127.0.0.1 - - [29/May/2017 23:33:02] "GET /socket.io/?EIO=4&transport=websocket HTTP/1.1" 500 3166 0.044977
(11312) accepted ('127.0.0.1', 34657)
connect  fd003dced4824092a7fd3aa0985ad769
0.6985820531845093 2.5365664000000026
Traceback (most recent call last):
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/eventlet/wsgi.py", line 507, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/engineio/middleware.py", line 47, in __call__
    return self.engineio_app.handle_request(environ, start_response)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/socketio/server.py", line 353, in handle_request
    return self.eio.handle_request(environ, start_response)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/engineio/server.py", line 252, in handle_request
    transport, b64)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/engineio/server.py", line 374, in _handle_connect
    ret = s.handle_get_request(environ, start_response)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/engineio/socket.py", line 89, in handle_get_request
    start_response)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/engineio/socket.py", line 136, in _upgrade_websocket
    return ws(environ, start_response)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/engineio/async_eventlet.py", line 14, in __call__
    return super(WebSocketWSGI, self).__call__(environ, start_response)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/eventlet/websocket.py", line 127, in __call__
    self.handler(ws)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/engineio/socket.py", line 218, in _websocket_handler
    raise reraise_exc
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/engineio/socket.py", line 204, in _websocket_handler
    self.receive(pkt)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/engineio/socket.py", line 56, in receive
    async=self.server.async_handlers)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/engineio/server.py", line 401, in _trigger_event
    return self.handlers[event](*args)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/socketio/server.py", line 513, in _handle_eio_message
    self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/socketio/server.py", line 449, in _handle_event
    self._handle_event_internal(self, sid, data, namespace, id)
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/socketio/server.py", line 452, in _handle_event_internal
    r = server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/home/adrian/miniconda3/envs/carnd/lib/python3.5/site-packages/socketio/server.py", line 481, in _trigger_event
    return self.handlers[namespace][event](*args)
  File "drive.py", line 76, in telemetry
    image.save('{}.jpg'.format(image_filename))
AttributeError: 'numpy.ndarray' object has no attribute 'save'
```

I have tried starting the sim first then running the `python drive.py ...`, and the other way around as well, command first-sim second. Nothing works.

Any help appreciated.

**Comment by domluna** [comment]
@adriantorrie It looks like `image` is a numpy array, perhaps you overrode it at some point. In any case you have to convert it back to an PIL image. I believe you can do that with 

```python
from PIL import Image
image = Image.fromarray(image)
```

**Comment by adriantorrie** [comment]
Ah forgot i had put this as an issue. Please close, user error. I had an erroneous line using cv2 to convert the image, which I removed.
